mtt/urls.py
from django.contrib import admin
from tournament import views
from tournament.admin import admin_site
from django.conf import settings
from django.urls import include, path
from django.views.decorators.cache import cache_page

from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/createround/<int:pk>/', views.CreateRoundView.as_view(), name='createround'),
    path('admin/', admin_site.urls),
    # path('', cache_page(30)(views.IndexView.as_view()), name='index'),
    # path('', views.IndexView.as_view(), name='index'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('player-registration/', views.PlayerRegistrationView.as_view(), name='player-registration'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('tables/', views.TablesView.as_view(), name='tables'),
]

# public page
if settings.PUBLIC_PAGE_CACHE_TIME is None:
    urlpatterns.append(path('', views.IndexView.as_view(), name='index'))
else:
    urlpatterns.append(path('', cache_page(settings.PUBLIC_PAGE_CACHE_TIME)(views.IndexView.as_view()), name='index'))

# debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

nonsolonumeri/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

tournament/models.py
import networkx as nx
import itertools
import random
from collections import Counter
from decimal import Decimal

from django.db import models

from django.core.validators import RegexValidator
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError

from django.utils.translation import gettext_lazy as _


# match types
NORMAL = 'N'
BYE = 'B'

# round visibility
HIDE = 'H'
HIDE_RESULTS = 'R'
SHOW = 'S'
VISIBILITY_CHOICES = (
    (HIDE, 'Hide'),
    (HIDE_RESULTS, 'Hide results'),
    (SHOW, 'Show'),
)


class Score:
    """
    A score of a team or a player.
    This class comprises a primary (more important) score, a secondary (less important) score,
    and a phantom score (used to break ties by hand, e.g. if a tie break is played).
    It also keeps track of the number of matches and (in the case of one match)
    of the type of match (normal/bye).
    """
    def __init__(self, primary=Decimal('0.0'), secondary=Decimal('0.0'), phantom=Decimal('0.0'), num_matches=0, match_type=None):
        self.primary = primary
        self.secondary = secondary
        self.phantom = phantom
        self.num_matches = num_matches
        self.match_type = match_type


    def raw(self):
        return (self.primary, self.secondary, self.phantom)


    def __repr__(self):
        return self.raw().__repr__()


    def __eq__(self, other):
        return self.primary == other.primary and self.secondary == other.secondary and self.phantom == other.phantom and self.num_matches == other.num_matches

    def __le__(self, other):
        if self.raw() != other.raw():
            return self.raw() < other.raw()
        return self.num_matches >= other.num_matches

    def __gt__(self, other):
        if other is 0:
            return self != Score()
        else:
            return not self <= other

    def __hash__(self):
        return hash((self.primary, self.secondary))

    def __add__(self, other):
        if other is 0:
            return self
        else:
            return Score(
                primary=self.primary+other.primary,
                secondary=self.secondary+other.secondary,
                phantom=self.phantom+other.phantom,
                num_matches=self.num_matches+other.num_matches
            )

    def __radd__(self, other):
        if other is 0:
            return self
        else:
            return self + other

    def to_int(self):
        """
        Integer representation of the score, used in round creation.
        The primary score weights much more than the secondary score.
        """
        return int(10*(100 * self.primary + self.secondary))



def score_counter_to_str(counter, hide_secondary=False):
    """
    Transform a counter of scores into a string, for display purposes.
    """
    if hide_secondary:
        return ', '.join('%s (%s)' % (entity.name, str(score.primary)) for (entity, score) in reversed(sorted(counter.items(), key=lambda x: x[1])))

    else:
        return ', '.join('%s (%s, %s)' % (entity.name, str(score.primary), str(score.secondary)) for (entity, score) in reversed(sorted(counter.items(), key=lambda x: x[1])))



class Tournament(models.Model):
    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=255, null=True, blank=True, default=None, help_text='Name to show on mobile devices.')

    creation_time = models.DateTimeField(auto_now_add=True)
    bye_score = models.DecimalField(max_digits=4, decimal_places=1, default=3, help_text='Score to assign for a bye.')

    description = models.TextField(null=True, blank=True, default=None, help_text='This appears at the beginning of the public page. You can use HTML tags.')
    default_round_visibility = models.CharField(max_length=2, choices=VISIBILITY_CHOICES, default=SHOW, help_text='Default visibility of newly generated rounds.')
    shown_players = models.PositiveIntegerField(null=True, blank=True, default=0, help_text='Number of players to show in the scoreboard. If no value is given, all players are shown. If 0, the player scoreboard is not shown.')
    player_scoreboard_description = models.TextField(null=True, blank=True, default=None, help_text='This appears at the beginning of the player scoreboard. You can use HTML tags.')

    # registration parameters
    is_registration_open = models.BooleanField(default=False)
    max_teams = models.PositiveIntegerField(null=True, blank=True, default=None, help_text='Maximum number of allowed teams during registration. If no value is given, the number is unlimited.')
    max_players_per_team = models.PositiveIntegerField(null=True, blank=True, default=0, help_text='Maximum number of allowed players per team during registration. If no value is given, the number is unlimited (probably unsupported!). If 0 is given, player registration is disabled.')    # TODO


    def __str__(self):
        return self.name

    def num_rounds(self):
        return Round.objects.filter(tournament=self).count()

    def can_register(self):
        return self.is_registration_open and (self.max_teams is None or Team.objects.count() < self.max_teams)

    def can_register_player(self):
        return self.is_registration_open and self.max_players_per_team > 0


    def team_scoreboard(self, public=False, fill_results=False):
        res = sum((match.team_scoreboard(public=public, fill_results=fill_results) for match in Match.objects.filter(round__tournament=self).prefetch_related('round', 'teamresult_set__team__player_set', 'teams')), Counter())
        for team in Team.objects.filter(active=True):
            if team not in res:
                res[team] = Score()
        return res

    def player_scoreboard(self, public=False):
        res = sum((match.player_scoreboard(public=public) for match in Match.objects.filter(round__tournament=self).prefetch_related('round', 'playerresult_set__player__team')), Counter())
        for player in Player.objects.filter(team__active=True):
            # add player if not present
            if player not in res:
                res[player] = Score()

            # add phantom score if present
            if player.phantom_score is not None:
                res[player] += Score(phantom=player.phantom_score)
        return res


    def create_round(self):
        """
        Create a new round for this tournament.
        """
        teams = Team.objects.filter(active=True).order_by('pk')
        tables = Table.objects.all()
        matches = Match.objects.filter(round__tournament=self)

        previous_pairs = set(match.team_pair() for match in matches)
        previous_byes = set(match.team_bye() for match in matches)

        previous_tables = {table: set() for table in tables}
        for match in matches:
            if match.table is not None:
                for team in match.teams.all():
                    previous_tables[match.table].add(team)

        ### pair teams ###
        if self.num_rounds() == 0:
            # random pairings
            team_queue = list(teams)
            random.shuffle(team_queue)
            pairs = []
            while len(team_queue) > 1:
                pairs.append((team_queue.pop(), team_queue.pop()))
            if len(team_queue) == 1:
                pairs.append((team_queue.pop(),))

        else:
            G = nx.Graph()
            G.add_nodes_from(teams)

            # analyze scoreboard
            scoreboard = self.team_scoreboard(public=False, fill_results=True) # pending results are considered as full victories for all teams
            # print("Scoreboard")
            # print(scoreboard)

            clusters = {} # clusters of teams with the same score
            for team in teams:
                score = scoreboard[team].to_int() # this is an integer score
                if score not in clusters:
                    clusters[score] = []
                clusters[score].append(team)

            # print(clusters)

            M = len(teams) * (max(clusters) - min(clusters)) + 1 # some big constant
            # print("M = %d" % M)

            score_to_pos = {}
            pos = 0
            for score in sorted(clusters):
                score_to_pos[score] = pos
                pos += 1

            # print(score_to_pos)

            for pair in itertools.combinations(teams, 2):
                if pair not in previous_pairs:
                    # create edge between teams
                    scores = tuple(scoreboard[team].to_int() for team in pair)
                    weight = - (max(scores) - min(scores)) * M ** score_to_pos[max(scores)]
                    G.add_edge(*pair, weight=weight)

            if len(teams) % 2 == 1:
                # add bye
                G.add_node(BYE)

                for team in teams:
                    if team not in previous_byes:
                        # create bye edge
                        score = scoreboard[team].to_int()
                        weight = - score * M ** pos
                        G.add_edge(team, BYE, weight=weight)

            # compute matching
            matching = nx.max_weight_matching(G, maxcardinality=True)
            pairs = list((a, b) if a != BYE and b != BYE else (a,) if b == BYE else (b,) for (a, b) in matching)

        # print(pairs)

        ### assign tables ###
        G = nx.Graph()
        G.add_nodes_from([pair for pair in pairs if len(pair) == 2])
        G.add_nodes_from(tables)

        for table in tables:
            for pair in pairs:
                if len(pair) == 2:
                    weight = table.priority # an integer between 0 and 100

                    if any(team in previous_tables[table] for team in pair):
                        # penalize this table
                        weight -= 1000

                    # create edge
                    G.add_edge(pair, table, weight=weight)

        # compute matching
        matching = nx.max_weight_matching(G, maxcardinality=True)

templates/admin_index.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "admin_style.css" %}">
{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">

<div class="module">
<table>
<caption>
<div class="section">Current tournament</div>
</caption>
{% if current_tournament %}
    <tr>
        <th scope="row">Current tournament: <a href="{% url 'admin:tournament_tournament_change' current_tournament.pk %}" class="rchangelink">{{ current_tournament }}</a></th>
        {% with num_rounds=current_tournament.num_rounds %}
        <td>{{ num_rounds }} round{{ num_rounds|pluralize }}</td>
        {% endwith %}
    </tr>

    <tr><td><a href="{% url 'admin:tournament_team_changelist' %}" class="changelink">Change teams</a></td><td></td></tr>
    <tr><td><a href="{% url 'admin:tournament_table_changelist' %}" class="changelink">Change tables</a></td><td></td></tr>
    <tr><td><a href="{% url 'admin:tournament_round_changelist' %}?tournament__id__exact={{ current_tournament.pk }}" class="changelink">Change rounds</a></td><td></td></tr>
    <tr><td><a href="{% url 'admin:tournament_match_changelist' %}?round__tournament__id__exact={{ current_tournament.pk }}" class="changelink">Change matches</a></td><td></td></tr>

    {% comment %}
    <tr><td><a href="{% url 'admin:tournament_tournament_actions' pk=current_tournament.pk tool='create_round' %}" class="addlink">Create a new round</a></td></tr>
    {% endcomment %}
    <tr><td><a href="{% url 'createround' pk=current_tournament.pk %}" class="addlink">Generate a new round</a> (can take a few seconds)</td><td>Default visibility: {{ current_tournament.get_default_round_visibility_display }}</td></tr>
{% else %}
    <th><td scope="row"><a href="{% url 'admin:tournament_tournament_add' %}" class="addlink">Create a new tournament</a></td><td></td></th>
{% endif %}
</table>
</div>

{% if current_tournament and current_tournament.num_rounds > 0 %}
{% with current_round=current_tournament.round_set.latest %}
<div class="module">
<table>
<caption>
<div class="section">Current round</div>
</caption>
    <tr>
        <th scope="row">Current round: <a href="{% url 'admin:tournament_round_change' current_round.pk %}" class="rchangelink">{{ current_round }}</a></th>
        <td>Visibility: {{ current_round.get_visibility_display }}</td>
        <td>Time: {{ current_round.scheduled_time }}</td>
    </tr>

    {% for match in current_round.match_set.all %}
        <tr>
            <td><a href="{% url 'admin:tournament_match_change' match.pk %}">{{ match }}</a></td>
            <td>{% if match.table %}{{ match.table }}{% endif %}</td>
            <td>{% if match.result %}{{ match.result }}{% endif %}</td>
        </tr>
    {% endfor %}
</table>
</div>
{% endwith %}
{% endif %}

{% if app_list %}
    {% for app in app_list %}
        <div class="app-{{ app.app_label }} module">
        <table>
        <caption>
            <a href="{{ app.app_url }}" class="section" title="{% blocktrans with name=app.name %}Models in the {{ name }} application{% endblocktrans %}">{{ app.name }}{% if app.name == 'Tournament' %} database{% endif %}</a>
        </caption>
        {% for model in app.models %}
            <tr class="model-{{ model.object_name|lower }}">
            {% if model.admin_url %}
                <th scope="row"><a href="{{ model.admin_url }}">{{ model.name }}</a></th>
            {% else %}
                <th scope="row">{{ model.name }}</th>
            {% endif %}

            {% if model.add_url %}
                <td><a href="{{ model.add_url }}" class="addlink">{% trans 'Add' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}

            {% if model.admin_url %}
                {% if model.view_only %}
                <td><a href="{{ model.admin_url }}" class="viewlink">{% trans 'View' %}</a></td>
                {% else %}
                <td><a href="{{ model.admin_url }}" class="changelink">{% trans 'Change' %}</a></td>
                {% endif %}
            {% else %}
                <td>&nbsp;</td>
            {% endif %}
            </tr>
        {% endfor %}
        </table>
        </div>
    {% endfor %}
{% else %}
    <p>{% trans "You don't have permission to view or edit anything." %}</p>
{% endif %}
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>{% trans 'Recent actions' %}</h2>
        <h3>{% trans 'My actions' %}</h3>
            {% load log %}
            {% get_admin_log 10 as admin_log for_user user %}
            {% if not admin_log %}
            <p>{% trans 'None available' %}</p>
            {% else %}
            <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if entry.is_deletion or not entry.get_admin_url %}
                    {{ entry.object_repr }}
                {% else %}
                    <a href="{{ entry.get_admin_url }}">{{ entry.object_repr }}</a>
                {% endif %}
                <br>
                {% if entry.content_type %}
                    <span class="mini quiet">{% filter capfirst %}{{ entry.content_type }}{% endfilter %}</span>
                {% else %}
                    <span class="mini quiet">{% trans 'Unknown content' %}</span>
                {% endif %}
            </li>
            {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>
{% endblock %}

templates/base.html
{% load i18n static %}

{% language 'it' %}
<!doctype html>
<html lang="it">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}?v=4">

    <title>{% block title %}{% endblock %}</title>

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>

    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">

    {% block head %}{% endblock %}
</head>

<body>

<nav class="navbar navbar-expand navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container">
        <!-- <a class="navbar-brand" href="{% url 'index' %}">
            <h1 class="text-nowrap d-none d-md-block">{% if tournament %}{{ tournament.name }}{% else %}Multi-table tournament{% endif %}</h1>
            <h1 class="d-md-none">{% if tournament.short_name %}{{ tournament.short_name }}{% elif tournament %}{{ tournament.name }}{% else %}MTT{% endif %}</h1>
        </a> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse navbar-content" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link tournament-name" href="{% url 'index' %}">
                    <h1 class="d-none d-md-block">{% if tournament %}{{ tournament.name }}{% else %}Multi-table tournament{% endif %}</h1>
                    <h1 class="d-md-none">{% if tournament.short_name %}{{ tournament.short_name }}{% elif tournament %}{{ tournament.name }}{% else %}MTT{% endif %}</h1>
                    </a>
                </li>
            </ul>
            {% block navbar %}{% endblock %}
        </div>
    </div>
</nav>

<div class="container mt-5 mb-3 content">

{% block content %}{% endblock %}

</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% comment %}
<script src="{% static 'script.js' %}"></script>
{% endcomment %}

</body>

</html>
{% endlanguage %}

templates/index.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}{{ tournament.name }}{% endblock %}


{% block navbar %}
<!-- <ul class="navbar-nav ml-auto d-none d-lg-block"> -->
<ul class="navbar-nav ml-auto">
    {% if tournament.is_registration_open %}
    <li class="nav-item">
        <a class="nav-link nav-link-registration navbar-button px-2" href="#registration">
            <img class="navbar-img" src="{% static 'registration.png' %}" /><div class="text-center">Iscrizioni</div>
        </a>
    </li>
    {% endif %}

    {% if team_scoreboard %}
    <li class="nav-item">
        <a class="nav-link nav-link-team navbar-button px-2" href="#team-scoreboard">
            <img class="navbar-img" src="{% static 'team.png' %}" /><div class="text-center">Classifica<br />squadre</div>
        </a>
    </li>
    {% endif %}

    {% if rounds %}
    <li class="nav-item">
        <a class="nav-link nav-link-rounds navbar-button px-2" href="#rounds">
            <img class="navbar-img" src="{% static 'clock.png' %}" />
            <div class="text-center navbar-button pt-2">Turni</div>
        </a>
    </li>
    {% endif %}

    {% if player_scoreboard %}
    <li class="nav-item">
        <a class="nav-link nav-link-player navbar-button px-2" href="#player-scoreboard">
            <img class="navbar-img" src="{% static 'player.png' %}" />
            <div class="text-center navbar-button">Classifica<br />individuale</div>
        </a>
    </li>
    {% endif %}
</ul>
{% endblock %}


{% block content %}

{% if tournament.description %}
<div class="description pt-3">
{{ tournament.description|safe }}
<hr />
</div>
{% endif %}


{% if tournament.is_registration_open %}
<h3 class="my-4" id="registration">Iscrizioni</h3>
<p>
{% if tournament.can_register %}
Su <a href="{% url 'registration' %}" class="link">questa pagina</a> puoi iscrivere una nuova squadra.<br />
{% else %}
È stato raggiunto il numero massimo di squadre.<br />
{% endif %}
{% if tournament.can_register_player %}
Su <a href="{% url 'player-registration' %}" class="link">questa pagina</a> puoi aggiungerti a una squadra già creata.
{% endif %}
</p>

{% if team_scoreboard or rounds or player_scoreboard %}
<hr />
{% endif %}
{% endif %}


{% if team_scoreboard %}
<h3 class="my-4 anchor" id="team-scoreboard">Classifica squadre</h3>

<div class="table-responsive">
<table class="table">
<thead>
    <tr>
    <th scope="col" class="text-center">#</th>
    <th scope="col">Squadra</th>
    <th scope="col" class="text-center">Incontri vinti</th>
    <th scope="col" class="text-center">Partite vinte</th>
    </tr>
</thead>
<tbody>
{% for team, score, rank in team_scoreboard %}
    <tr>
        <th scope="row" class="text-center">{{ rank }}</th>
        <td class="clickable" data-toggle="modal" data-target="#team-modal-{{ team.id }}">{{ team }}</td>
        <td class="text-center">{{ score.primary }} / {{ score.num_matches }}</td>
        <td class="text-center">{{ score.secondary }}</td>
    </tr>
{% endfor %}
</tbody>
</table>
</div>

{% if rounds or player_scoreboard %}
<hr />
{% endif %}
{% endif %}


{% for round in rounds %}
<h3 class="my-4 anchor" {% if forloop.first %}id="rounds"{% endif %}>Turno {{ round.number }}{% if round.scheduled_time %}
<small class="text-muted">({{ round.scheduled_time|date:"l" }} alle {{ round.scheduled_time|date:"G:i" }})</small>{% endif %}</h3>

<div class="table-responsive">
<table class="table">
<thead>
    <tr>
    <th scope="col" style="width: 50%">Partita</th>
    <th scope="col" style="width: 30%">Tavolo</th>
    <th scope="col" style="width: 20%" class="text-center">Risultato</th>
    </tr>
</thead>
<tbody>
{% for match in round.valid_matches %}
    <tr>
        <td>{{ match }}</td>
        <td>{{ match.table|default_if_none:"-" }}</td>
        <td class="text-center">{% if round.show_results %}{{ match.result|default_if_none:"-" }}{% else %}-{% endif %}</td>
    </tr>
{% endfor %}
</tbody>
</table>
</div>
{% endfor %}
{% if rounds and player_scoreboard %}
<hr />
{% endif %}


{% if player_scoreboard %}
<h3 class="my-4 anchor" id="player-scoreboard">Classifica individuale</h3>

{% if tournament.player_scoreboard_description %}
<div class="description pb-2">
{{ tournament.player_scoreboard_description|safe }}
</div>
{% endif %}


<div class="table-responsive">
<table class="table">
<thead>
    <tr>
    <th scope="col" class="text-center">#</th>
    <th scope="col">Giocatore</th>
    <th scope="col">Squadra</th>
    <th scope="col" class="text-center">Partite vinte</th>
    </tr>
</thead>
<tbody>
{% for player, score, rank in player_scoreboard %}
    <tr>
        <th scope="row" class="text-center">{{ rank }}</th>
        <td>{{ player.name }}</td>
        <td>{{ player.team.name }}</td>
        <td class="text-center">{{ score.primary }}</td>
        {# <td class="text-center">{{ score.num_matches }}</td> #}
    </tr>
{% endfor %}
</tbody>
</table>
</div>
{% endif %}


{# Team modals #}
{% for team in teams %}
<div class="modal fade" id="team-modal-{{ team.id }}" tabindex="-1" role="dialog" aria-labelledby="label-team-{{ team.id }}" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="label-team-{{ team.id }}"><b>{{ team.name }}</b></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for player in team.player_set.all %}
            {{ player.name }}{% if player.is_captain %} (capitano){% endif %}<br />
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}

templates/player_registration.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}Iscrizione{% endblock %}

{% block content %}
<div class="my-4">
<h3 class="mb-4">Iscrizione singolo giocatore</h3>

{% if tournament.can_register_player %}

{% if available_teams %}
<p>Puoi aggiungerti a una squadra{% if tournament.max_players_per_team %} con meno di {{ tournament.max_players_per_team }} giocatori{% endif %}.<br />
La lista delle squadre è consultabile sulla <a href="{% url 'index' %}" class="link">pagina principale</a> (clicca su una squadra per vedere la lista dei suoi giocatori).</p>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Iscriviti">
</form>
{% else %}
<p>Al momento non ci sono squadre{% if tournament.max_players_per_team %} con meno di {{ tournament.max_players_per_team }} giocatori{% endif %}.<br />
Puoi tornare alla <a href="{% url 'index' %}">pagina principale</a>.</p>
{% endif %}
{% else %}
<p>Al momento non è possibile iscrivere nuovi giocatori.<br />
Puoi tornare alla <a href="{% url 'index' %}">pagina principale</a>.</p>
{% endif %}

</div>

{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}Iscrizione{% endblock %}

{% block content %}
<div class="my-4">
<h3 class="mb-4">Iscrizione squadra</h3>

{% if tournament.can_register %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Iscrivi questa squadra">
</form>
{% else %}
<p>{% if tournament.is_registration_open %}È stato raggiunto il numero massimo di squadre.{% else %}Le iscrizioni sono chiuse.{% endif %}<br />
Puoi tornare alla <a href="{% url 'index' %}">pagina principale</a>.</p>
{% endif %}
</div>

{% endblock %}

templates/tables.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}Lista dei tavoli{% endblock %}

{% block content %}
<div class="my-4">
<h3 class="mb-4">Lista dei tavoli</h3>

{% comment %}
<ul>
{% for table in object_list %}
    <li><b>{{ table }}</b> {{ table.description }}</li>
{% empty %}
    <li>Non ci sono tavoli.</li>
{% endfor %}
</ul>
{% endcomment %}

<div class="table-responsive">
<table class="table">
{% for table in object_list %}
    <tr>
        <th scope="row">{{ table.name }}</th>
        <td>{{ table.description|default_if_none:"" }}</td>
    </tr>
{% endfor %}
</table>
</div>

</div>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}Iscrizione{% endblock %}

{% block content %}
<div class="my-4">
<h3 class="mb-4">Iscrizione</h3>

<p>L'iscrizione è avvenuta con successo. Grazie!<br />
Se hai bisogno di effettuare delle modifiche, contatta gli organizzatori.</p>
</div>

<div class="my-4">
<p>Ora puoi tornare alla <a href="{% url 'index' %}" class="link">pagina principale</a>.</p>
</div>

{% endblock %}